### ISSUE TITLE
Don't know if this is an issue

### ISSUE THREAD

**Issue by FrankieLaw** [ChristopherBThai/Discord-OwO-Bot#101]
OwO doesn't seem to be responding to any commands.
I don't exactly know how OwO works code wise.  

Is it down?
Do I have to reset it?
Do I have to reinvite?

**Comment by justnaa** [comment]
The [OwO Bot Support discord](https://discord.gg/VKesv7J) is a better place to ask this question. The reason why she was unresponsive was that she had problems with the Discord API.
