### ISSUE TITLE
OWO command issue

### ISSUE THREAD

**Issue by pritstift93** [ChristopherBThai/Discord-OwO-Bot#12]
Hi

I tried setting a special animal as a pet but the bot returns message saying the animal doesnt exist. Cant special animals be set as pets?

**Comment by ChristopherBThai** [comment]
You can mouse over the pet to get their names, or, if you're on a phone, you can tap and hold the message to copy the names!

**Comment by ChristopherBThai** [comment]
And for future reference, you can use the command 'owo feedback' or join our guild by 'owo guildlink' for faster replies!
