### ISSUE TITLE
OWO NOT ONLINE

### ISSUE THREAD

**Issue by Ark989** [ChristopherBThai/Discord-OwO-Bot#142]
today I can't use owo bot, because it's offline. someone please help me with. I don't know what happened. 

![image](https://user-images.githubusercontent.com/77665896/105014383-f352e600-5a72-11eb-9623-8074a4719767.png)

**Comment by Oaaku** [comment]
Check their server for announcement

**Comment by NekoAlosama** [comment]
@Ark989 OwO bot back. might need to make it rejoin the server

**Comment by NekoAlosama** [comment]
@Ark989 Close the issue, it's done.
