### ISSUE TITLE
Pets gaining a battle's worth of xp upon friendly battle

### ISSUE THREAD

**Issue by FortitudeinGold** [ChristopherBThai/Discord-OwO-Bot#146]
I first had this happen a few weeks ago while testing a distorted lethality comp: as you can see by the screenshots, I added them to the team, later checked the team again. The streak didn't go up, I wouldn't have risked losing a 17k streak like that; I only did a test battle against a friendly vstaff comp. Yet as you can see, I got 200 xp from a battle, some battle, and catchup multiplied it for an instant L.2 progression. I figured it likely wasn't huge or consistent and could have been a product of the lag from a few hours prior, until today, when I had someone reproduce it....
![Screenshot_20210206-184611](https://user-images.githubusercontent.com/62676684/107135128-f0e2ef80-68ac-11eb-9b11-c4a2cf950be3.png)
![Screenshot_20210206-184625](https://user-images.githubusercontent.com/62676684/107135136-f7716700-68ac-11eb-8b14-40ce827741b9.png)
![Screenshot_20210206-184635](https://user-images.githubusercontent.com/62676684/107135139-fd674800-68ac-11eb-8c8a-0933f981da31.png)
![Screenshot_20210206-184647](https://user-images.githubusercontent.com/62676684/107135143-06f0b000-68ad-11eb-9be9-cf4381a26e58.png)

I can't attach the mp4 of her completing it but it was much the same: add pets to team, friendly battle, check team, pets levelled up inexplicably

**Comment by sfk-steelsong** [comment]
So, I can't replicate this.  Friendly battles do not give exp on the current codebase.

However, keep in mind that the enemy team gets exp too when you fight them at the same values you do (no streak bonus) and I can confirm that catch up exp is in effect for the opposing team. So most likely someone fought you and lost while this was happening.

**Comment by FortitudeinGold** [comment]
> So, I can't replicate this. Friendly battles do not give exp on the current codebase.
> 
> However, keep in mind that the enemy team in random battles gets exp too when you fight them at the same values you do (no streak bonus) and I can confirm that catch up exp is in effect for the opposing team. So most likely someone fought you and lost while this was happening.
> 
> ![image](https://user-images.githubusercontent.com/16299710/107866838-a7f5e280-6e3a-11eb-8e13-bfde9299169a.png)
> 
> in this battle, snail and tiger were given 200 exp and elephant was given 540 xp.

noted, I had no idea this was possible. Closing the issue
