### ISSUE TITLE
Developer CLA assigns rights to SAP?

### ISSUE THREAD

**Issue by mmarseglia** [ChristopherBThai/Discord-OwO-Bot#150]
Why does the CLA assign all rights, works, etc. to the company SAP?

"Copyright License. You hereby grant, and agree to grant, to SAP a non-exclusive, perpetual, irrevocable, worldwide, fully-paid, royalty-free, transferable copyright license to reproduce, prepare derivative works of, publicly display, publicly perform, and distribute your Contributions and such derivative works, with the right to sublicense the foregoing rights through multiple tiers of sublicensees."

**Comment by hamdrew** [comment]
Looks like this was reported in #123, which is still open. Hopefully the maintainer can address this before SAP steals our owos.

**Comment by mmarseglia** [comment]
closing as duplicate of #123
