### ISSUE TITLE
[QOL/Balancing] Pls Remove cash quests pls pls pls pls pls

### ISSUE THREAD

**Issue by FortitudeinGold** [ChristopherBThai/Discord-OwO-Bot#157]
At some point in time, I'm sure cash quests actually gave you a good value for your completions. At some time, those quests probably actually gave you a noticeable boost in cowoncy. After all, that's the only reasonable explanation for why they exist, especially at their current values.

I don't think I need to state how outdated they are; they're something on par with weapon selling (honestly, who would sell a fabled weapon for another shot at blackjack). But like with weapon selling, I don't think the solution is to buff them, but to remove the feature entirely. The economy is massively inflated and the daily bonuses, votes included, and even levelup and patreon boosts are severely undervalued proportionately. Buffing these would merely give people more money to buy nothing. We have a few things to buy: wallpapers (only a few million to get all of them.), rings (Once you get fabled, what's the point besides grinding to make your inventory massive? It's still pointless, and many simply buy commons.), and patreon...Which is interesting, because the ability to grind to buy from sellers that won't always be around isn't exactly a great balancing tool.

Thus we have the economy: way too much money with nothing to buy. There's no sense in it whatsoever. Purging the majourity of all cowoncy is too complex and would compromise the patreon sale system; and, of course, you'd be doing it proportionately, so the relatively poor would suffer unnecessarily. Besides, pet tiers would need to be turned to sell at far lower rates.

So you could add things to buy, making high cowoncy quests possibly worth it for some. But that involves adding entire sets of new features, balancing their prices and ensuring people actually want to grind for them. Again, too complex, and largely unnecessary.

So the solution is to simply remove cash quests. You could argue removing these would allow more high reward quests to be rolled, possibly making them op, but I think we're past that with the addition of shard quests. A single box for getting actioned is still hailed as better than 50,000 cowoncy for literally anything else. Please, for all our sanities, remove them. Please

**Comment by sfk-steelsong** [comment]
not all quests have to be "good", this is by design.  Also cash quests get the users that only use the bot for gambling to test out other areas of the bot, which is part of what quests were designed for.

**Comment by FortitudeinGold** [comment]
> not all quests have to be "good", this is by design. Also cash quests get the users that only use the bot for gambling to test out other areas of the bot, which is part of what quests were designed for.

Bad quests are great, but can we not be forced to complete them at the very least? 200 cowoncy is a joke. Even to someone who thinks 50k cowoncy is rich (if you can find them, levelup cash is plenty to work with for gamble only players), it's just plain terrible. It ruins the grind especially, knowing that if I hunt too much, I'll get "too many mythics" and finish a quest I intended to save. If we can't see them gone, can we at least have a way to prevent this
![Screenshot_20210223-164443](https://user-images.githubusercontent.com/62676684/108928783-9ad5b200-75f7-11eb-8584-fb5c99118389.png) I mean come on

**Comment by FortitudeinGold** [comment]
If we're getting Lex's quest lock feature that'll do
