### ISSUE TITLE
Empowering gem bug

### ISSUE THREAD

**Issue by Riverness** [ChristopherBThai/Discord-OwO-Bot#18]
Issue: Near depleted empowering gem doubling more animals than it has charges for.

Common Empowering Gem in active gem position 1:
![image](https://user-images.githubusercontent.com/45148827/48675896-40c02980-eb70-11e8-8616-8a2b7ba6bce3.png)

Tried it again with another empowering gem and it was the same outcome this time with 2 charges left and still working for all animals.

Uncommon Empowering Gem in active gem position 3:
![image](https://user-images.githubusercontent.com/45148827/48676027-cbedef00-eb71-11e8-9dbc-3da75445aecc.png)

Expected outcome: Since only 1 (2) charge(s) remains on the empowering gem, it is expected that only 1 (2) of the animals to trigger the x2 effect and the other 6 (5) to not, resulting in 8 (9) animals being hunted but as both pictures show I got 14 as if the empowering gem had 7 charges. 

Reproducing steps: Get an empowering gem to near depletion and hunt animals.

**Comment by ChristopherBThai** [comment]
I am aware of this bug, but I decided to make it a feature! I didn't want to go through the hassle of changing it. Thank you though!
