### ISSUE TITLE
Bot not online.

### ISSUE THREAD

**Issue by FarhanDevelopment** [ChristopherBThai/Discord-OwO-Bot#198]
Please help me.
No error !

What happened? 
![IMG_20210609_221319_447.jpg](https://user-images.githubusercontent.com/84755087/121381469-f3934580-c96f-11eb-913a-5e5865160492.jpg)

**Comment by HARISHKUMAR-PY** [comment]
TRY TO RESTART BRO

**Comment by FarhanDevelopment** [comment]
> TRY TO RESTART BRO

I did restart it 3 times.
Do you try it and worked bot online?
Please give your discord, chat  me 😭 pls.

**Comment by FarhanDevelopment** [comment]
Huh

**Comment by HARISHKUMAR-PY** [comment]
WHAT CHAT BRO

**Comment by HARISHKUMAR-PY** [comment]
YES I TRYED IN MY BOT AND IT GOT ONLINE SO DEBUG AND RESTART AGAIN BRO

**Comment by FarhanDevelopment** [comment]
> YES I TRYED IN MY BOT AND IT GOT ONLINE SO DEBUG AND RESTART AGAIN BRO

Chat in discord.

**Comment by FarhanDevelopment** [comment]
> YES I TRYED IN MY BOT AND IT GOT ONLINE SO DEBUG AND RESTART AGAIN BRO

I trued it many times still not online
