### ISSUE TITLE
CODE GORE!!

### ISSUE THREAD

**Issue by LordLucass** [ChristopherBThai/Discord-OwO-Bot#201]
Code gore. I believe that this repository should be deleted, or at least a "gore code" warning in its readme!!

**Comment by Togira123** [comment]
> Code gore. I believe that this repository should be deleted, or at least a "gore code" warning in its readme!!

What does that mean?

**Comment by JustSamuel** [comment]
> What does that mean?

My man is mad that  a personal project doesn't adhere to company coding standards.

**Comment by Togira123** [comment]
> > What does that mean?
> 
> 
> 
> My man is mad that  a personal project doesn't adhere to company coding standards.
> 
> 
lmao this is hilarious

**Comment by Mirnich** [comment]
And than you see in his repository big projects with clean code... It is hilarious indeed

**Comment by iiLearner** [comment]
seek help

**Comment by LordLucass** [comment]
The code in this repository is horrible, they should delete it as soon as possible, I left this project almost blind!!!

**Comment by Togira123** [comment]
@ChristopherBThai why don't you close that issue👀

**Comment by LordLucass** [comment]
He must be embarrassed of his horrible code to come here and close it...format the code, it's horrible! You must not have a clue about clean code concepts in javascript!!!

**Comment by Mirnich** [comment]
I'm not defending the cleanliness of code, because it's far from it, but this code was written while he was studying I believe. So can't really expect to write like an expert but should he clean it? Definitely! Anyway looking forward to your refactoring LordLucass 🥳

**Comment by JustSamuel** [comment]
We have a saying in Dutch, "Beter kunnen is zelf doen" which in this cases roughly translates to :  "Make the pull request yourself lmao"

**Comment by LordLucass** [comment]
> I'm not defending the cleanliness of code, because it's far from it, but this code was written while he was studying I believe. So can't really expect to write like an expert but should he clean it? Definitely! Anyway looking forward to your refactoring LordLucass

I won't refactor the code, why should I if the repository owner himself doesn't know how to do it!? By the way, I study and my code is not a piece of shit thrown on the monitor, just like this repository!

**Comment by LordLucass** [comment]
> We have a saying in Dutch, "Beter kunnen is zelf doen" which in this cases roughly translates to : "Make the pull request yourself lmao"

No thanks, I don't want to waste time rewriting the bot, just teasing on this issue 🤣 🤣 🤣

**Comment by iiLearner** [comment]
someone teach him the concepts of open source code

**Comment by LordLucass** [comment]
> someone teach him the concepts of open source code

https://dev.to/deepaksisodiya/5-best-practices-for-clean-coding-in-javascript-26am
https://github.com/ryanmcdermott/clean-code-javascript

Np

**Comment by ChristopherBThai** [comment]
Brb shutting down owo bot due to 🍝
