### ISSUE TITLE
Code being used as plural in the readme

### ISSUE THREAD

**Issue by wasi-master** [ChristopherBThai/Discord-OwO-Bot#236]
> Here are the *codes* for OwO Bot!

This is bugging me for a while. I believe it should be "Here is the source code for OwO Bot".\
Quote from [Is it wrong to use the word "codes" in programming context?](https://english.stackexchange.com/a/20456):

In computer science, "code" is used as a mass noun, specifying the collection of instructions in a specific arrangement as a whole and in no specific quantity. Whether > t's one line of code or ten pages, it is still referred to as code, not codes.\
When "codes" is used in computer science, it typically refers to values or constants used to specify a trait, access or properties, though in my experience, the actual > ame of those types of items is used over the word "codes". For example, instead of:
>Use these codes to specify the read/write permissions of the file.
 
 You would write/say:
 
>Use these constants to specify the read/write permissions of the file.
>Or:
>Use this enumeration to specify the read/write permissions of the file.
 
 With regard to the use of "code":
 
>Use this code to open a file.

>Use these functions in the source code to access the database.

>This program code needs to be tidied up.

Now I don't want to be a asshole by saying this is very wrong and should not be used but this is just something that has been bothering me so I am just putting it out there.

**Comment by Smeagol2069** [comment]
In my opinion that is intentional due to the style grammatical style of OwO Bot.

**Comment by wasi-master** [comment]
I guess that's a valid point
