### ISSUE TITLE
Quest Can't Be Completed

### ISSUE THREAD

**Issue by LocalShaman** [ChristopherBThai/Discord-OwO-Bot#24]
I got the 'have a friend emote to you' quest a while ago and for the life of me I can't figure out how to finish it. I've been emoted to numerous times since receiving the quest to no avail. Neither the Discord reactions nor owo bot's emote commands do anything and I'm getting really frustrated... is there even a way to complete the quest?

**Comment by ChristopherBThai** [comment]
Yes, the correct command is have someone use a command from the 'action' section! 

Ex. owo hug @LocalShaman

**Comment by ChristopherBThai** [comment]
We also have a server for questions and stuff so feel free to join with 'owo guildlink'!
