### ISSUE TITLE
Hunt Bot Max Level Trait Bug

### ISSUE THREAD

**Issue by kopitp** [ChristopherBThai/Discord-OwO-Bot#25]
When a trait in the hunt bot is at it's maximum level, essence can still be used to try and upgrade the trait, even though it is at max level. Should cap at max and not allow the player to accidentally try and upgrade the trait.

**Comment by ChristopherBThai** [comment]
Yes! I'm aware of this issue and it will be fixed soon!

**Comment by kopitp** [comment]
Awesome. Thanks.

**Comment by ChristopherBThai** [comment]
This issue has been solved by 7708c5e3416d60c698fb7355dcb3ad7b07df3dd1
