### ISSUE TITLE
Lottery bug maybe?

### ISSUE THREAD

**Issue by ZX7s** [ChristopherBThai/Discord-OwO-Bot#256]
You lost the lottery...
You had a 0.14% chance to win 101465283 cowoncy...
The winner was Hu*** with a 0.1% chance to win!

:) How
![Screenshot_20220211-224756_Discord](https://user-images.githubusercontent.com/99494948/153624576-4e5f63ee-37a4-40e7-81b4-ac61944b8494.png)

**Comment by ZeInhumane** [comment]
uwu
