### ISSUE TITLE
No option to disable owo from all channels at once

### ISSUE THREAD

**Issue by kalyan-gupta** [ChristopherBThai/Discord-OwO-Bot#266]
Why there is no command/settings for the bot to disable it over server wide except for specific channel?

Even if I disable it individually on all channels, it still sends messages for ranking? (Note: I didn't configure my server channels individuals on allowed/ permitted roles, but the bot shall have all commands so it will be flexible?)

**Comment by Smeagol2069** [comment]
Hi @kalyan-gupta,

There is not a way to disable all commands at once currently. You are welcome to suggest/upvote an existing suggestion for it in the support server. Currently to disable all commands in a channel you can use the `owo disable all` command, this must be sent in each channel. 

To disable the level up messages you can say `owo level disable`, if you ever want to turn it back on you can say `owo level enable`.  This is server-wide and only needs to be said once. 

Hope this helps! Feel free to reach out in the support server for if you have any more questions (Invite found with `owo guildlink`)

**Comment by kalyan-gupta** [comment]
Thanks , hope it will be added soon, as it's regarding user experience
