### ISSUE TITLE
Hunt bot, Radar upgrade, #% incorrectly displays or bad value catch?

### ISSUE THREAD

**Issue by Starkiller1236** [ChristopherBThai/Discord-OwO-Bot#273]
Apologies if I seem new to this, first post..

Starting point was a level 0 fresh hunt bot, 
Began spending my 500,000 animal essence in bulks, 
Upgrade levels jumped by a few at a time,
Noticed the radar values looked sus.

Investigation on owobot.fandom reveals that it is not correct or at least not displaying correctly.

Anything I can do to resolve this? Reset hunt bot? Trust that it's actually correct? GG I got scammed lmao?

Any help would be appreciated.

![SmartSelect_20220506-153851_Discord](https://user-images.githubusercontent.com/105081228/167213586-db489b26-da17-4d6e-9c49-74b5fd689223.jpg)
![SmartSelect_20220506-153825_Discord](https://user-images.githubusercontent.com/105081228/167213607-7dfdf2b6-373e-45ca-abc3-f7152a9a6620.jpg)
![SmartSelect_20220506-153750_Discord](https://user-images.githubusercontent.com/105081228/167213615-83529605-4337-4479-af23-25f2e0f6bd1f.jpg)
![SmartSelect_20220506-151019_Discord](https://user-images.githubusercontent.com/105081228/167213626-54c541c8-8f42-4219-8f11-e7da119cea9b.jpg)
![SmartSelect_20220506-153458_Brave](https://user-images.githubusercontent.com/105081228/167213637-af93a761-1ed8-44b8-ac0a-44a872d51cab.jpg)

**Comment by notchem** [comment]
it seems like these are just rounding 'issues'

**Comment by Starkiller1236** [comment]
> it seems like these are just rounding 'issues'

That makes a lot of sense, if only I could count zeros and see that myself before posting..
F, 
Thank you!
