### ISSUE TITLE
My friend got banned for no reason

### ISSUE THREAD

**Issue by oujashya** [ChristopherBThai/Discord-OwO-Bot#275]
Myfriend got banned he had 10 mill owo pls unban his acc username jadx#6969

**Comment by notchem** [comment]
this isn’t the place to ask for ban appeals, please join the bot support server and ask in the help channel.

**Comment by Cyrooo** [comment]
👀

**Comment by oujashya** [comment]
where is the server

**Comment by notchem** [comment]
in the help channel
