### ISSUE TITLE
Staff of purity + mtap not recovering wp in turn 1

### ISSUE THREAD

**Issue by jay-ir** [ChristopherBThai/Discord-OwO-Bot#342]
![Screenshot_2023-03-21-06-48-30-565_com android chrome](https://user-images.githubusercontent.com/128431172/226483004-d7f2549a-3981-407a-8cd9-9753f52199d2.jpg)
![Screenshot_2023-03-21-06-48-55-733_com android chrome](https://user-images.githubusercontent.com/128431172/226483023-bafcc383-0103-4d79-87f7-0e496733b093.jpg)

The effect of mtap isn't triggered at turn 1 of battle even though debuff is successful and damage has clearly been dealt to enemy. This behaviour is consistent and as such is detrimental to pstaff.

**Comment by Caviarbro** [comment]
This happens with every passive using postAttack function. 

I don't know exactly why and where the bug appears but it's something near this line.

https://github.com/ChristopherBThai/Discord-OwO-Bot/blob/e21e4c3bdf312d40009671f10d03f1c83a71e1ee/src/commands/commandList/battle/WeaponInterface.js#L332

**Comment by Caviarbro** [comment]
> ![Screenshot_2023-03-21-06-48-30-565_com android chrome](https://user-images.githubusercontent.com/128431172/226483004-d7f2549a-3981-407a-8cd9-9753f52199d2.jpg) ![Screenshot_2023-03-21-06-48-55-733_com android chrome](https://user-images.githubusercontent.com/128431172/226483023-bafcc383-0103-4d79-87f7-0e496733b093.jpg)
> 
> The effect of mtap isn't triggered at turn 1 of battle even though debuff is successful and damage has clearly been dealt to enemy. This behaviour is consistent and as such is detrimental to pstaff.

Fixed in PR:
https://github.com/ChristopherBThai/Discord-OwO-Bot/pull/340/commits/d45d0ec27845a4649526da41b7edde4ae13dac8b

**Comment by jay-ir** [comment]
Fixed
