### ISSUE TITLE
Example mysql schema file out of date

### ISSUE THREAD

**Issue by laod** [ChristopherBThai/Discord-OwO-Bot#47]
Would it be possible to get a fresh mysql dump, please? The contents of json/example_secret_files/mysql-database-tables no longer match the code. I hacked my way through the missing tables but it would be nice if people trying to contribute didn't have to.

Similarly, the sample owo-animals.json is not working. My update (although you'll likely want something better - emoji ids are wrong, patreons can't get gem/special): https://github.com/laod/Discord-OwO-Bot/blob/lucky-random/json/example_secret_files/owo-animals.json

**Comment by ChristopherBThai** [comment]
Sure thing! I'll update the mysql dumps, and see what's up with the example owo-animals.js

**Comment by ChristopherBThai** [comment]
Should be good to go now!

**Comment by laod** [comment]
Fantastic! Thank you.
