### ISSUE TITLE
Eightball command sends the user ID and not the name

### ISSUE THREAD

**Issue by joaquimnet** [ChristopherBThai/Discord-OwO-Bot#56]
The eightball command sends the user id and not a mention.

![image](https://user-images.githubusercontent.com/11339121/63123855-5720d780-bf80-11e9-9ff8-8c9f90b42e10.png)

I'd make a PR but your license looks really complicated.

**Comment by ChristopherBThai** [comment]
Thank you! Fixed in 4e23ff527377af5c887ee26d29dfc645d10c9c16
