### ISSUE TITLE
Bans / No Contact Details

### ISSUE THREAD

**Issue by TheRealPhil** [ChristopherBThai/Discord-OwO-Bot#59]
_Long story short:_
I lately earned myself a perma ban out of my own stupidity and now regret it with the will of never doing it again. I regret it and sadly realised it only after it happened. Now i want to contact the Dev personaly to maybe find a solution on it. 
_The problem:_
I can't message him/her, because there are no contact details given and on the OwO Bot support server, i can't tag him or else i'll get kicked.
Please give me the opportunity to change or other people to contact you directly via email or something.
Sincerely, Phil.

**Comment by Demi670** [comment]
Feels bad about your ban (good luck), but yea contact details would be great. Sometimes my request gets lost in the flood of messages.
