### ISSUE TITLE
Can't manual battle

### ISSUE THREAD

**Issue by mdatsev** [ChristopherBThai/Discord-OwO-Bot#74]
Trying to set battlesetting auto=false doesn't work. The code is commented out in the battlesetting file.  Is this intentionaly disabled? Why? And if so the info in owo help is not updated to match the actual settings.
![image](https://user-images.githubusercontent.com/22428036/71752775-01928c00-2e89-11ea-8a23-2b790aca1835.png)
![image](https://user-images.githubusercontent.com/22428036/71752824-3d2d5600-2e89-11ea-8836-d344dbfa24a2.png)

**Comment by ChristopherBThai** [comment]
Manual battles are no longer available to avoid rate limits! I still need to update the battle images to reflect these changes.
