### ISSUE TITLE
rateLimit solution

### ISSUE THREAD

**Issue by LinkOps** [ChristopherBThai/Discord-OwO-Bot#81]
I'm fairly new (and quickly becoming a regular at the game) nOticing the recurring issue of rate-limiting I think an intermediary solution would be to default the battle commands to speed=instant/display=compact which would, in turn, reduce the message calls down greatly.

Personally does having the battle update for every round (of which some occur so quickly you never see each iteration) make much of a difference? I'm more interested in the end report and that would only result in a single message quota call opposed to the average 7 calls I would have seen with interactive (or whatever the default is called)

Maybe during rate limit issues/weekend/peak periods, we could trial the instant/compact method without the time increase thus keeping the experience somewhat the same but in theory, greatly reducing the quota utilisation counts.

More than happy to discuss further or attempt to trial and monitor the differences somehow if needed be.

Regards,

Link

**Comment by ChristopherBThai** [comment]
Old issue, but this issue has been resolved by Discord staff!
